//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchSchedule()
        {
            this.MatchResults = new HashSet<MatchResults>();
        }
    
        public int MatchID { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> Player1ID { get; set; }
        public Nullable<int> Player2ID { get; set; }
        public Nullable<int> Team1ID { get; set; }
        public Nullable<int> Team2ID { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchResults> MatchResults { get; set; }
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
