//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResults
    {
        public int ResultID { get; set; }
        public Nullable<int> MatchID { get; set; }
        public string Score { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<System.TimeSpan> GameTime { get; set; }
    
        public virtual MatchSchedule MatchSchedule { get; set; }
    }
}
