//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStats
    {
        public int StatID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
        public Nullable<int> MatchesPlayed { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> TournamentPosition { get; set; }
        public string Achievements { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
