//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rankings
    {
        public int RankingID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
