//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int RecordID { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public string RecordType { get; set; }
        public string RecordValue { get; set; }
    
        public virtual Tournaments Tournaments { get; set; }
    }
}
