//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPlayer
    {
        public int IdRequest { get; set; }
        public int PlayerId { get; set; }
        public string NickName { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Request Request { get; set; }
    }
}
