//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament421_SemenovaOlesya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public Nullable<int> Type_id { get; set; }
        public Nullable<int> Game_id { get; set; }
        public Nullable<int> Prize_fund { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Tournament_type Tournament_type { get; set; }
    }
}
